[general]
import = [
	"~/.config/alacritty/themes/tokyo_night.toml",
]
live_config_reload = true

[window]
dimensions = { columns = 95, lines = 30 }
dynamic_padding = true
decorations = "Full"
dynamic_title = true

[scrolling]
multiplier = 5

[font]
normal = {family = "Literation Mono Nerd Font" }
size = 13

[selection]
save_to_clipboard = true

[cursor]
style = {shape = "Block", blinking = "On"}
unfocused_hollow = true
thickness = 0.05

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

#[keyboard]
#bindings = [
#{key = "v", mods = "Control", action = "Paste"},
#{key = "c", mods = "Control", action = "Copy"},
#{key = "N", mods = "Control|Shift", action = "CreateNewWindow"},
#{key = "F", mods = "Control|Shift", action = "ToggleFullscreen"}
#]
