# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#1a1b26'
red     = '#FF0040'
green   = '#00ff88'
yellow  = '#ffcc00'
blue    = '#00bbff'
magenta = '#ad8ee6'
cyan    = '#00ffff'
white   = '#ffffff'

# Bright colors
[colors.bright]
black   = '#565f89'
red     = '#ff1166'
green   = '#00ffaa'
yellow  = '#ffdd00'
blue    = '#00ddff'
magenta = '#bb9af7'
cyan    = '#00ffee'
white   = '#ffffff'
